domains = ["kehitys.localhost"]
localDomain = "kehitys.localhost"
projectName = "kehitys"
remoteDomain = "kehitys.jcore.fi"
remoteHost = "kehitys@vs.bojaco.com"
remotePath = "files"
theme = "ilme"
dbPrefix = "7q3_"
pluginGit = ["lohko"]
pluginExclude = ["ruudukko"]
pluginInstall = "remote"
wpImage = "jcodigi/wordpress:8.4"
